### ISSUE TITLE
无法录制快手直播

### ISSUE THREAD

**Issue by SxitDark** [chenfan0/fideo-live-record#10]
显示“直播间不存在”
实际上该直播间正在直播
![image](https://github.com/user-attachments/assets/caf25beb-5c13-4ba7-8e64-89248ddf1f62)
[同类型的工具](https://github.com/ihmily/DouyinLiveRecorder)也出现了类似的问题

**Comment by chenfan0** [comment]
我这里测试是，可以正常录制的

**Comment by SxitDark** [comment]
似乎不是特定直播间的问题
自家的电信公网ipv4、电信5g、邻居家的移动均无法录制但能用浏览器观看
~这下我成小丑了~

**Comment by SxitDark** [comment]
似乎不是特定直播间的问题
自家的电信公网ipv4、电信5g、邻居家的移动均无法录制但能用浏览器观看
~这下我成小丑了~

**Comment by chenfan0** [comment]
那可能是你的ip被风控了，快手很容易就风控

**Comment by SxitDark** [comment]
> 那可能是你的ip被风控了，快手很容易就风控

我又研究了一下，需要cookie才能正常录制
