### ISSUE TITLE
抖音电台直播和VR直播能支持吗？

### ISSUE THREAD

**Issue by zhouzhili** [chenfan0/fideo-live-record#14]
目前好像没有能支持抖音电台直播和VR直播的，大佬能支持下吗

**Comment by chenfan0** [comment]
给个直播链接看看？

**Comment by chenfan0** [comment]
> > 给个直播链接看看？
> 
> https://live.douyin.com/833441543071 这个直播间，手机上可以看，电脑上不显示

电台的新版可以支持，vr不支持

**Comment by Eyion** [comment]
何时支持微信视频号直播
