### ISSUE TITLE
Unable to modify the title and file name Once a project is created

### ISSUE THREAD

**Issue by JabyBaii** [chenfan0/fideo-live-record#16]
Once a new recording is created, the title and file name cannot be modified even when it is paused or not recording. I can only delete and rebuild it. Can you fix this?

**Comment by chenfan0** [comment]
The title cannot be modified, which is expected, but the filename can be modified. What is your fideo version？

**Comment by JabyBaii** [comment]
Thank you. It is acceptable that the title cannot be modified. I tested it again with v0.2.7 and the file name can be changed successfully.
