### ISSUE TITLE
无法录制Bigo直播视频

### ISSUE THREAD

**Issue by lucky-666666** [chenfan0/fideo-live-record#18]
作者你好，软件目前好像无法录制Bigo的直播视频，显示直播间不存在或者未开播,但实际这个主播有开播的

**Comment by chenfan0** [comment]
你是哪个直播间地址
<img width="859" alt="image" src="https://github.com/user-attachments/assets/d94bf389-3539-44c9-9598-e42066cc5ed6">
我这可以正常录制

**Comment by lucky-666666** [comment]
可以录制了  原来是地址格式写错

**Comment by lucky-666666** [comment]
作者大大 能不能开发一下 陌陌直播 录制  麻烦你了
