### ISSUE TITLE
Bug以及建议

### ISSUE THREAD

**Issue by lucky-666666** [chenfan0/fideo-live-record#23]
Bug以及建议
一、①每次打开软件,上一次没点停止监控,下一次打开无法点击关闭停止监控,必须重启软件才能关闭这个链接的监控
②如果主播正在开播,一开启软件就显示录制中,但它实际并没有在录,必须要重启一次软件才能正常操作
③如果软件重新开启后,显示录制中或者监控中,要停止以上操作,停止不了并且关闭软件点击右上角XX要按好几下XX才能关闭软件,总之重启软件解决一切
二、已存在的链接无法进行标题、线路、文件名的更改
三、无法进行搜索检索，建议设置可关键字搜索
四、建议录制时添加自动识别并创建主播名字或ID文件夹
五、作者大大能否添加 陌陌 这个平台录制

**Comment by chenfan0** [comment]
你的版本号是多少

**Comment by lucky-666666** [comment]
> 你的版本号是多少? 文件名是支持更改的，但是标题不支持更改。
v0.2.9最新版

**Comment by chenfan0** [comment]
那你添加一下QQ交流群吧

**Comment by lucky-666666** [comment]
好的晚点

**Comment by chenfan0** [comment]
有想要新增的平台麻烦在这个issue写 https://github.com/chenfan0/fideo-live-record/issues/8

**Comment by lucky-666666** [comment]
开发着你好，能否在下一次更新的时候，改进以上建议。谢谢啦
