### ISSUE TITLE
直播中断后录制的视频出现花屏

### ISSUE THREAD

**Issue by ilbuco** [chenfan0/fideo-live-record#24]
开发者你好，昨天我在使用 fideo-0.2.9 版本进行直播录制时，遇到一个问题：当直播过程中主播网络短暂中断后，恢复连接后的录像画面全部出现了花屏，直到录制结束。
我判断该问题是由网络中断引起的，因为花屏开始的时间点恰好与网络中断的时间点吻合，并且中断后直至结束都是花屏画面。
具体来说，直播过程中主播的网络连接中断了几秒钟。在网络恢复后，直播画面正常，录制也继续进行。然而，在直播结束后查看录像文件时，发现从网络中断的时间点开始，直到录制结束，画面都出现了花屏现象，无法正常观看。
![01](https://github.com/user-attachments/assets/be7549ea-dabb-48ef-97b1-0ca3cdb26e6c)
![02](https://github.com/user-attachments/assets/8f05444a-3566-4982-91bd-3ed22a4658ce)

**Comment by chenfan0** [comment]
这个应该是分辨率改变了，导致了花屏了
