### ISSUE TITLE
录制转码，直播录制格式问题

### ISSUE THREAD

**Issue by yunhaihaihai** [chenfan0/fideo-live-record#26]
你好，请问是否可以不强制转码，因为一是任务如果中途中断，录制的文件就会开始转码，转码结束才能继续录制，二是大量任务同时转码会使电脑处于卡顿状态，还有能否可以使用TS格式来录制直播，使用三天总体感觉这个录制工具非常不错，稍微提一点小小的建议，希望作者可以接纳

**Comment by yunhaihaihai** [comment]
补充一点，假如因为某些原因直播录制中断，转码后任务就停了不再监控，重新开启还得手动开

**Comment by chenfan0** [comment]
> 补充一点，假如因为某些原因直播录制中断，转码后任务就停了不再监控，重新开启还得手动开

现在好像只有手动点击停止才会暂停监控，因为主播下播或者其他原因并不会停止监控的

**Comment by chenfan0** [comment]
> 你好，请问是否可以不强制转码，因为一是任务如果中途中断，录制的文件就会开始转码，转码结束才能继续录制，二是大量任务同时转码会使电脑处于卡顿状态，还有能否可以使用TS格式来录制直播，使用三天总体感觉这个录制工具非常不错，稍微提一点小小的建议，希望作者可以接纳

后续会提供 是否 在结束录制后转码为mp4的选择功能

**Comment by WLaoDuo** [comment]
> > 补充一点，假如因为某些原因直播录制中断，转码后任务就停了不再监控，重新开启还得手动开
> 
> 现在好像只有手动点击停止才会暂停监控，因为主播下播或者其他原因并不会停止监控的

有时候会出现这种停止录播的情况。请问可以修改 “停止”状态为“重新监控”状态吗？
![图片](https://github.com/user-attachments/assets/60c6398b-293f-437d-b2e8-774c4474a112)
