### ISSUE TITLE
YY直播一到PK和团战就花屏

### ISSUE THREAD

**Issue by 2660785300** [chenfan0/fideo-live-record#27]
跪求作者解决
![微信图片_20240804194428](https://github.com/user-attachments/assets/9ec0476b-d77f-4793-8cb9-f20a1d26897e)

**Comment by chenfan0** [comment]
后续版本会可以控制是否在录制结束后转码为 mp4 的功能，你可以将自动转码的功能关闭，flv格式的应该就不会有花屏的问题了
