### ISSUE TITLE
[bug]停止录制，当前线路错误。（推测是网络波动/代理不稳定）

### ISSUE THREAD

**Issue by WLaoDuo** [chenfan0/fideo-live-record#28]
[版本commit d887cdf8503bcc051bcc6df1901a7aff2eae84c6]
推测因为代理不稳/网络波动（没找到日志记录），有时候会出现这种停止录播的情况，重新手动启动就能开始录制。请问在哪里可以修改 “停止”状态为“重新监控”状态？
![图片](https://github.com/user-attachments/assets/60c6398b-293f-437d-b2e8-774c4474a112)

**Comment by chenfan0** [comment]
目前如果错误是线路错误的话就会停止，不会继续监控。后续版本可能会重新尝试几次，然后持续失败再停止
