### ISSUE TITLE
录制twitch直播会丢帧

### ISSUE THREAD

**Issue by yunhaihaihai** [chenfan0/fideo-live-record#31]
已经录了三天了，录制的twitch直播每三秒会丢一帧卡顿，另外一个朋友录制也是如此，希望作者可以帮忙解决一下谢谢

**Comment by chenfan0** [comment]
你是什么版本的？我这里本地测试并不会有这个问题，这是我录制的视频

https://github.com/user-attachments/assets/2bf55e28-d682-4b46-a3cb-4019cbbef9ea
