### ISSUE TITLE
淘宝的COOKIE怎么添加？

### ISSUE THREAD

**Issue by mimi180** [chenfan0/fideo-live-record#39]
淘宝的COOKIE是从哪里怎么添加上去的？下载淘宝的会提示COOKIE

**Comment by chenfan0** [comment]
https://github.com/chenfan0/fideo-live-record/blob/main/README-CN.md#-%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96cookie

**Comment by chenfan0** [comment]
淘宝的需要通过在 控制台 输入 copy(document.cookie) 这个命令获取

**Comment by chenfan0** [comment]
![tabbao](https://github.com/user-attachments/assets/9cd4f04d-577d-4169-b054-0dbd721ef264)
