### ISSUE TITLE
一直检测不到快手录制。

### ISSUE THREAD

**Issue by Guan-jinquan** [chenfan0/fideo-live-record#41]
一直检测不到快手录制。

**Comment by chenfan0** [comment]
可能是你ip被风控了，也可能是你开梯子了

**Comment by Guan-jinquan** [comment]
> 可能是你ip被风控了，也可能是你开梯子了

该怎么解决呢，我另外一个直播录制软件录制快手不会被风控，但是他需要登录快手才能录制。

**Comment by chenfan0** [comment]
最新版本添加了请求过快的提示，可以了解无法录制的原因

**Comment by TeslaLyon** [comment]
> > 可能是你ip被风控了，也可能是你开梯子了
> 
> 该怎么解决呢，我另外一个直播录制软件录制快手不会被风控，但是他需要登录快手才能录制。

hello  另一个可以使用的软件是什么？
