### ISSUE TITLE
导致鼠标卡顿等系统 IO 问题的性能问题反馈

### ISSUE THREAD

**Issue by egbertwong** [chenfan0/fideo-live-record#51]
开启这个软件之后，如果同时浏览器开启太多标签页很容易会导致系统假死，现象为鼠标特别延迟和卡顿，几乎无法操作，但是如果电脑在播放一些内容或者界面中有一些加载动效则正常。怀疑为系统资源吃满，CPU占用过高，IO资源吃的比较满。相关情况可见此贴：[windows11 鼠标卡顿](https://v2ex.com/t/1060010)。看起来可能是 Windows 11 的调度问题，但是经常由这个软件触发。希望有可能的话针对这个问题做一些优化。

系统：Windows 11
CPU：i9-13980HX
内存：32G
GPU：RTX 4060 LAPTOP

**Comment by chenfan0** [comment]
这个实在是不好排查
