### ISSUE TITLE
tiktok真的支持吗

### ISSUE THREAD

**Issue by hahah-ha** [chenfan0/fideo-live-record#58]
我用tiktok的直播地址发现无法使用
地址格式：https://www.tiktok.com/@XXXXXX/live
<img width="1410" alt="image" src="https://github.com/user-attachments/assets/dad600e1-e1ac-4ee9-86ff-1c46990e8395">

**Comment by chenfan0** [comment]
最新版本修复了一下，你试一试

**Comment by hahah-ha** [comment]
> 最新版本修复了一下，你试一试

请问mac系统版本有要求吗，新版本的我安装不了

<img width="441" alt="image" src="https://github.com/user-attachments/assets/bcd14f3e-1b6b-46ae-b0b1-d6bd090686bd">

**Comment by hahah-ha** [comment]
> 最新版本修复了一下，你试一试

试了一下还是不行，报的错误变了，这是一个不需要登陆就能观看的直播间，我在浏览器没有登陆可以正常观看：
![image](https://github.com/user-attachments/assets/79bb2b07-cf30-4388-ac2f-92b31af79b17)

<img width="874" alt="image" src="https://github.com/user-attachments/assets/bf7b77cf-0665-4962-a5b0-d68ca99e6b3c">

**Comment by chenfan0** [comment]
你有开全局代理吗
<img width="900" alt="image" src="https://github.com/user-attachments/assets/fc3be4be-6482-40d9-ae64-a39c014ae1e9">

**Comment by hahah-ha** [comment]
你好，请问是在哪里开全局代理呢，是我的梯子吗







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月19日(星期六) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenfan0/fideo-live-record] tiktok真的支持吗 (Issue #58)














 
你有开全局代理吗
 image.png (view on web)

**Comment by chenfan0** [comment]
是的，你的梯子要开启全局代理，录制项需要填写 proxy

**Comment by hahah-ha** [comment]
好的，谢谢，能给个proxy的参考格式吗，我不太清楚是填什么类型，我对着格式找，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月19日(星期六) 凌晨0:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenfan0/fideo-live-record] tiktok真的支持吗 (Issue #58)














 
是的，你的梯子要开启全局代理，录制项需要填写 proxy

**Comment by chenfan0** [comment]
http://127.0.0.1:7890

**Comment by hahah-ha** [comment]
非常感谢大佬，解决问题了，方便发个收款码吗，想一个小红包表达一下谢意



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月19日(星期六) 凌晨0:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chenfan0/fideo-live-record] tiktok真的支持吗 (Issue #58)














 
http://127.0.0.1:7890

**Comment by chenfan0** [comment]
感谢
![image](https://github.com/user-attachments/assets/9b99c4e9-1cd7-4f64-b765-41052f7f005a)
