### ISSUE TITLE
期望新增的平台

### ISSUE THREAD

**Issue by chenfan0** [chenfan0/fideo-live-record#8]

**Comment by chenfan0** [comment]
instagram

**Comment by miserytk** [comment]
希望大大能加afreecatv平台，谢谢。

**Comment by FanChen0119** [comment]
> 希望大大能加afreecatv平台，谢谢。

提供一下平台地址
是否需要登录才能观看

**Comment by chenfan0** [comment]
> 希望大大能加afreecatv平台，谢谢。

- 提供一下平台的地址
- 是否需要登录才能观看
- 是否需要代理

**Comment by miserytk** [comment]
> > 希望大大能加afreecatv平台，谢谢。
> 
> * 提供一下平台的地址
> * 是否需要登录才能观看
> * 是否需要代理

网址：https://www.sooplive.co.kr
需要登录也需要代理。谢谢大大
