### ISSUE TITLE
期望新增的功能

### ISSUE THREAD

**Issue by chenfan0** [chenfan0/fideo-live-record#9]

**Comment by faithxie** [comment]
希望能定时自动开始录制，定时结束。

**Comment by chenfan0** [comment]
> 希望能定时自动开始录制，定时结束，每天都录制。需求来源：某主播开播时，没法看，想录制后没事慢慢看，或者混剪视频。

现在直播间未直播是会开启监控录制的，并且直播结束后也会自动开启监控录制

**Comment by lucky-666666** [comment]
作者你好，软件目前好像无法录制Bigo的直播视频，显示直播间不存在或者未开播

**Comment by Eyion** [comment]
好像没有预览功能

**Comment by chenfan0** [comment]
> 好像没有预览功能

这个可能后续会支持用户复制直播流地址，然后自行使用软件进行预览

**Comment by Eyion** [comment]
直播地址是否会经常变化？（我把抖快，视频号直播地址加到OBS播放，通常第2天就失效了）
如果经常变化，能否实现软件监控获取？

**Comment by chenfan0** [comment]
> 直播地址是否会经常变化？（我把抖快，视频号直播地址加到OBS播放，通常第2天就失效了） 如果经常变化，能否实现软件监控获取？

你说的地址是指直播流的地址还是直播间的地址，直播流的地址每次开播都会变化，甚至有的变化的更频繁。对于fideo来说不需要用户去管直播流地址，只需要填对应直播间地址即可。

**Comment by Eyion** [comment]
1. https://live.kuaishou.com/u/KPL704668133
2. https://ws-origin.pull.yximgs.com/gifshow/kwai_actL_ksle_20240816174008_OUx_strL_hd2000.flv?wsTime=66c5da0d&wsSecret=e6419856086d96ecf75f5fbad4e87256&stat=hGMIkqBIwY90IjjI6nbvQ0osJtAxZoiSUL4VWMXlJqLPO7SCPzlImdHJgR7gByGM&tsc=origin&highTraffic=2&oidc=watchmen&sidc=2756&srcStrm=e0LLuQGo-l4&fd=0&ss=s20&kabr_spts=-5000
1是直播间地址，2是直播流地址？
OBS里填1是没法观看的，2好像会变的

**Comment by chenfan0** [comment]
是的，2是会变的每次直播都会变，甚至不同时刻去获取都会变，没办法让它不变

**Comment by Eyion** [comment]
1是不会变的吧，监控直播只需要1就可以？预览或者说直接观看就需要2？
而视频号是否1也会变

**Comment by chenfan0** [comment]
是的监控只需要1就行，预览就得用2，视频号我不确定，还没空去搞

**Comment by Eyion** [comment]
视频号因为没有直接提供直播间的地址，能获取的只是类似2这样的地址，所以像小绿点这样的软件也是要每次使用时再检测，而抖快这些平台基本只要加1次就可以

**Comment by chenfan0** [comment]
-  [ ] 支持录制过程出现错误时重试三次
-  [ ] 支持分辨率改变时重新录制

**Comment by gzasyf** [comment]
Looking forward to adding MP4 recording functionality and the ability to adjust recording resolution and bitrate.
期待增加录制MP4功能，并且可以调整录制的分辨率和码率。

**Comment by kekexixili9527** [comment]
可不可以直接加一个录制音频的功能，感谢您所做成的软件，他真的非常好用，实时监测直播间，有的时候我只想要直播间的音频，希望可以考虑一下这个建议

**Comment by leeBuli** [comment]
淘宝 cookie 怎么获取呀
